export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";
export const GET_THONG_TIN_NGUOI_DUNG = "SGET_THONG_TIN_NGUOI_DUNG";
export const GET_THONG_TIN_DAT_VE = "GET_THONG_TIN_DAT_VE";
